#!/bin/sh
uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua

#开启nginx
[ ! -e /usr/bin/wget-ssl  ] && ln -s /usr/bin/wget  /usr/bin/wget-ssl
[[ ! -e /etc/config/ssl/ca.cer && -d /etc/acme/*.sysblz.com ]] && ln -s /etc/acme/*.sysblz.com/fullchain.cer  /etc/config/ssl/ca.cer
[[ ! -e /etc/config/ssl/ca.key && -d /etc/acme/*.sysblz.com ]] && ln -s /etc/acme/*.sysblz.com/*.sysblz.com.key  /etc/config/ssl/ca.key
/etc/init.d/nginx start
/etc/init.d/nginx enable

sed -i 's#https://downloads.openwrt.org#https://mirrors.sysblz.com#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i 's/snapshots/openwrt/g'  /etc/opkg/distfeeds.conf

opkg update